apiVersion: v1
kind: Service
metadata:
  name: ratings-data-service
  labels:
    name: ratings-data-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: ratings-data
  type: LoadBalancer
