server:
  port: 8082

spring:
  application:
    name: ratings-data
  zipkin:
    base-url: http://localhost:9411/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka/
    healthcheck:
      enabled: true