server:
  port: 8080

spring:
  application:
    name: ratings-data
  zipkin:
    base-url: http://zipkin-server/

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server/eureka/
    healthcheck:
      enabled: true